// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTlJwmF4sagvWUl8xCIHQfHHulMdkFQP8',
    appId: '1:457176302697:web:0258e8e24efc255a708ef8',
    messagingSenderId: '457176302697',
    projectId: 'fitmore-85114',
    authDomain: 'fitmore-85114.firebaseapp.com',
    storageBucket: 'fitmore-85114.firebasestorage.app',
    measurementId: 'G-MG7PDMWKQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAvxIyTv6_KRsxRxuOlGXbeBaPRxzfc5Q',
    appId: '1:457176302697:android:2bd7ea2bb975b189708ef8',
    messagingSenderId: '457176302697',
    projectId: 'fitmore-85114',
    storageBucket: 'fitmore-85114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATVOtgYo7YQdovNAqFJCgb7RMa3VVKzw4',
    appId: '1:457176302697:ios:62783183309bb2ec708ef8',
    messagingSenderId: '457176302697',
    projectId: 'fitmore-85114',
    storageBucket: 'fitmore-85114.firebasestorage.app',
    iosBundleId: 'com.example.fitmoreAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATVOtgYo7YQdovNAqFJCgb7RMa3VVKzw4',
    appId: '1:457176302697:ios:62783183309bb2ec708ef8',
    messagingSenderId: '457176302697',
    projectId: 'fitmore-85114',
    storageBucket: 'fitmore-85114.firebasestorage.app',
    iosBundleId: 'com.example.fitmoreAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZK1TSrczj0J0Xo7kN_bIXSAusFdarE8U',
    appId: '1:457176302697:web:0933d00144502ce6708ef8',
    messagingSenderId: '457176302697',
    projectId: 'fitmore-85114',
    authDomain: 'fitmore-85114.firebaseapp.com',
    storageBucket: 'fitmore-85114.firebasestorage.app',
    measurementId: 'G-JWNHCQ29BM',
  );
}
